# Generated by .github/homebrew/tap.sh in carp-dk/carp-cli, from the v0.2.1 release.
# Do not edit: the next release overwrites this file.
class Carp < Formula
  desc "Client for the Copenhagen Research Platform"
  homepage "https://carp.dk"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/carp-dk/carp-cli/releases/download/v0.2.1/carp-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "ffcebb33ec4dadc208fe9dcab425bf8c7b3a756def36f309103fdac78b6a7dd4"
    end

    on_intel do
      url "https://github.com/carp-dk/carp-cli/releases/download/v0.2.1/carp-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "dff65b864438e11b21cac49d40489a5e12bb3331157ad0557ae09da17f5e62a4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/carp-dk/carp-cli/releases/download/v0.2.1/carp-0.2.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1a2713fd5e8031e7e3bf99cbdd8f217940f92bdb94ec568d869c99ca57f4b079"
    end

    on_intel do
      url "https://github.com/carp-dk/carp-cli/releases/download/v0.2.1/carp-0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a610e46ac8193dfe868689b2f7778d9471c1de8d59d25e19ef49ad9b63862a43"
    end
  end

  def install
    bin.install "carp"
    doc.install "README.md"

    # "carp completions <shell>" writes the script to stdout. Homebrew runs it
    # once per shell it knows about and installs what comes back, so tab
    # completion works from the install rather than from a line in a dotfile.
    generate_completions_from_executable(bin/"carp", "completions")
  end

  test do
    assert_match "carp #{version}", shell_output("#{bin}/carp --version")
    assert_match "studies", shell_output("#{bin}/carp --help")
  end
end
